name: website hosting

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  website-hosting:
    name: change
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: |
          ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server Over SSH
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
        cd /var/www/html
        git fetch --all
        git reset --hard origin/main
        sudo systemctl restart apache2
        EOF
